# Generated by Django 3.2.5 on 2021-07-31 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('factor', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'usage_types',
                'managed': True,
                'unique_together': {('name', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_emissions', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usages', to='usages.usagetype')),
            ],
            options={
                'db_table': 'usage',
                'managed': True,
            },
        ),
    ]
